import AppKit
import Foundation
import UniformTypeIdentifiers

/// A decoded snapshot of what is currently on the pasteboard.
enum PasteboardPayload: Equatable, Sendable {
    case text(String)
    case url(URL)
    case image(data: Data)
}

/// What was read from the pasteboard, plus best-effort attribution.
struct PasteboardSnapshot: Equatable, Sendable {
    let payload: PasteboardPayload
    let sourceApplication: String?
}

/// The seam between Clickit and `NSPasteboard`.
///
/// Everything that touches the real system pasteboard lives behind this
/// protocol so the monitor and restore paths can be tested without a running
/// window server.
@MainActor
protocol PasteboardServicing: AnyObject {
    /// Monotonically increasing counter that macOS bumps on every write.
    var changeCount: Int { get }

    /// Reads and classifies the current contents, or `nil` when the pasteboard
    /// holds nothing Clickit supports.
    func read() -> PasteboardSnapshot?

    /// Writes a payload and returns the resulting change count so the caller
    /// can recognise — and ignore — its own write.
    @discardableResult
    func write(_ payload: PasteboardPayload) -> Int
}

@MainActor
final class PasteboardService: PasteboardServicing {
    private let pasteboard: NSPasteboard
    private let frontmostBundleIdentifier: @MainActor () -> String?

    init(
        pasteboard: NSPasteboard = .general,
        frontmostBundleIdentifier: @escaping @MainActor () -> String? = {
            NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        }
    ) {
        self.pasteboard = pasteboard
        self.frontmostBundleIdentifier = frontmostBundleIdentifier
    }

    var changeCount: Int { pasteboard.changeCount }

    /// The informal flavours from <http://nspasteboard.org> that applications use
    /// to tell clipboard managers not to record a write. Password managers mark
    /// their copies `ConcealedType`; honouring it is the difference between
    /// Clickit staying out of a vault's way and quietly archiving its secrets.
    private static let optOutTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    func read() -> PasteboardSnapshot? {
        guard !isMarkedDoNotRecord else { return nil }
        guard let payload = readPayload() else { return nil }
        return PasteboardSnapshot(payload: payload, sourceApplication: frontmostBundleIdentifier())
    }

    private var isMarkedDoNotRecord: Bool {
        guard let types = pasteboard.types else { return false }
        return !Self.optOutTypes.isDisjoint(with: types)
    }

    /// Classification order is deliberate.
    ///
    /// A file copied in Finder carries a `fileURL` *and* sometimes image data,
    /// so file URLs are resolved before image data to avoid recording a Finder
    /// copy as a screenshot. Conversely a real screenshot carries image data
    /// and no URL, so it falls through to the image branch.
    private func readPayload() -> PasteboardPayload? {
        if let url = readURL() {
            return .url(url)
        }
        if let data = readImageData() {
            return .image(data: data)
        }
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(string)
        }
        return nil
    }

    private func readURL() -> URL? {
        if let url = NSURL(from: pasteboard) as URL?, url.scheme != nil {
            return url
        }
        // Safari and most browsers put the address on the pasteboard as a plain
        // string without the URL flavour, so the string is parsed as a fallback.
        guard let string = pasteboard.string(forType: .string) else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(where: \.isWhitespace),
              let url = URL(string: trimmed),
              let scheme = url.scheme,
              ["http", "https", "file", "ftp", "mailto"].contains(scheme.lowercased()),
              url.host != nil || scheme.lowercased() == "mailto"
        else { return nil }
        return url
    }

    private func readImageData() -> Data? {
        if let png = pasteboard.data(forType: .png), !png.isEmpty {
            return png
        }
        // Screenshots and most in-app image copies arrive as TIFF; normalise to
        // PNG once here so the storage layer only ever deals with one format.
        guard let tiff = pasteboard.data(forType: .tiff),
              let bitmap = NSBitmapImageRep(data: tiff),
              let png = bitmap.representation(using: .png, properties: [:]),
              !png.isEmpty
        else { return nil }
        return png
    }

    @discardableResult
    func write(_ payload: PasteboardPayload) -> Int {
        pasteboard.clearContents()
        switch payload {
        case .text(let string):
            pasteboard.setString(string, forType: .string)
        case .url(let url):
            // Write both flavours: the URL type for apps that ask for it, and
            // the plain string so Command-V into a text field behaves normally.
            pasteboard.writeObjects([url as NSURL])
            pasteboard.setString(url.absoluteString, forType: .string)
        case .image(let data):
            pasteboard.setData(data, forType: .png)
        }
        return pasteboard.changeCount
    }
}
