import AppKit
import XCTest
@testable import Clickit

/// Exercises the real `PasteboardService` against a private `NSPasteboard`
/// rather than `NSPasteboard.general`, so classification and the do-not-record
/// conventions are verified against the actual system API without disturbing
/// the developer's clipboard.
@MainActor
final class PasteboardServiceTests: XCTestCase {
    private var pasteboard: NSPasteboard!
    private var service: PasteboardService!

    override func setUp() async throws {
        try await super.setUp()
        pasteboard = NSPasteboard.withUniqueName()
        service = PasteboardService(pasteboard: pasteboard) { "com.example.Source" }
    }

    override func tearDown() async throws {
        pasteboard.releaseGlobally()
        pasteboard = nil
        service = nil
        try await super.tearDown()
    }

    // MARK: - Classification

    func testPlainTextIsReadAsText() {
        pasteboard.clearContents()
        pasteboard.setString("just some words", forType: .string)

        XCTAssertEqual(service.read()?.payload, .text("just some words"))
    }

    func testSourceApplicationIsAttached() {
        pasteboard.clearContents()
        pasteboard.setString("anything", forType: .string)

        XCTAssertEqual(service.read()?.sourceApplication, "com.example.Source")
    }

    func testBareURLStringIsReadAsURL() throws {
        pasteboard.clearContents()
        pasteboard.setString("https://example.com/page", forType: .string)

        let expected = try XCTUnwrap(URL(string: "https://example.com/page"))
        XCTAssertEqual(service.read()?.payload, .url(expected))
    }

    /// A sentence that merely mentions a link is text, not a link.
    func testTextContainingAURLIsStillText() {
        pasteboard.clearContents()
        pasteboard.setString("see https://example.com for details", forType: .string)

        XCTAssertEqual(service.read()?.payload, .text("see https://example.com for details"))
    }

    func testStringWithoutASupportedSchemeIsText() {
        pasteboard.clearContents()
        pasteboard.setString("example.com", forType: .string)

        XCTAssertEqual(service.read()?.payload, .text("example.com"))
    }

    func testPNGDataIsReadAsImage() throws {
        let png = try makePNG()
        pasteboard.clearContents()
        pasteboard.setData(png, forType: .png)

        guard case .image(let data)? = service.read()?.payload else {
            return XCTFail("Expected an image payload")
        }
        XCTAssertEqual(data, png)
    }

    /// Screenshots and most in-app image copies arrive as TIFF.
    func testTIFFDataIsNormalisedToPNG() throws {
        pasteboard.clearContents()
        pasteboard.setData(try makeTIFF(), forType: .tiff)

        guard case .image(let data)? = service.read()?.payload else {
            return XCTFail("Expected an image payload")
        }
        XCTAssertFalse(data.isEmpty)
        XCTAssertEqual(data.prefix(8), Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]), "not a PNG header")
    }

    // MARK: - Content that must be ignored

    func testEmptyPasteboardReadsAsNil() {
        pasteboard.clearContents()

        XCTAssertNil(service.read())
    }

    func testWhitespaceOnlyStringIsIgnored() {
        pasteboard.clearContents()
        pasteboard.setString("   \n\t  ", forType: .string)

        XCTAssertNil(service.read())
    }

    /// Password managers mark their writes with this flavour to ask clipboard
    /// managers to stay out of the way.
    func testConcealedContentIsNotRecorded() {
        pasteboard.clearContents()
        pasteboard.setString("correct horse battery staple", forType: .string)
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))

        XCTAssertNil(service.read())
    }

    func testTransientContentIsNotRecorded() {
        pasteboard.clearContents()
        pasteboard.setString("temporary", forType: .string)
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))

        XCTAssertNil(service.read())
    }

    func testAutoGeneratedContentIsNotRecorded() {
        pasteboard.clearContents()
        pasteboard.setString("generated", forType: .string)
        pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))

        XCTAssertNil(service.read())
    }

    // MARK: - Writing

    func testWritingTextBumpsTheChangeCountAndRoundTrips() {
        let before = service.changeCount
        let after = service.write(.text("restored text"))

        XCTAssertGreaterThan(after, before)
        XCTAssertEqual(after, service.changeCount)
        XCTAssertEqual(pasteboard.string(forType: .string), "restored text")
    }

    /// URLs are written in both flavours so that Command-V into a plain text
    /// field still produces the address.
    func testWritingAURLAlsoWritesTheString() throws {
        let url = try XCTUnwrap(URL(string: "https://example.com/page"))
        service.write(.url(url))

        XCTAssertEqual(pasteboard.string(forType: .string), "https://example.com/page")
        XCTAssertEqual(service.read()?.payload, .url(url))
    }

    func testWritingAnImageRoundTrips() throws {
        let png = try makePNG()
        service.write(.image(data: png))

        XCTAssertEqual(pasteboard.data(forType: .png), png)
    }

    // MARK: - Helpers

    private func makeBitmap() throws -> NSBitmapImageRep {
        let bitmap = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: 4,
            pixelsHigh: 4,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        )
        return try XCTUnwrap(bitmap)
    }

    private func makePNG() throws -> Data {
        try XCTUnwrap(makeBitmap().representation(using: .png, properties: [:]))
    }

    private func makeTIFF() throws -> Data {
        try XCTUnwrap(makeBitmap().representation(using: .tiff, properties: [:]))
    }
}
